import theme from '@/styles/Theme';
import { SXMap } from '@/constants';

const SX: SXMap = {
  tab_wrapper: {
    position: 'relative',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: { xs: '40px 20px 20px 20px', sm: '40px 20px 20px 20px', md: '20px 5px 5px 5px' },
  },
  header_container: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    gap: '12px',
    marginBottom: '8px',
  },
  tab_title: {
    fontSize: { xs: '18px', sm: '18px', md: '20px', lg: '22px' },
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  context_badges_container: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
  },
  user_badge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 14px',
    borderRadius: '10px',
    backgroundColor: 'rgba(135, 154, 238, 0.08)',
    border: '1px solid rgba(135, 154, 238, 0.2)',
    transition: 'all 0.2s ease',
  },
  user_badge_label: {
    fontSize: '13px',
    fontWeight: 500,
    color: theme.palette.text.secondary,
  },
  user_badge_value: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#1e20ac',
    cursor: 'pointer',
    '&:hover': {
      color: theme.palette.primary.main,
      textDecoration: 'underline',
      textUnderlineOffset: '4px',
    },
  },

  filter_box: {
    width: '100%',
    mt: '20px',
    display: 'flex',
    flexDirection: { xs: 'column', sm: 'row' },
    gap: '10px',
  },
  select: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'start',
  },
  select_title: {
    fontSize: '12px',
    fontWeight: 600,
    marginBottom: '8px',
    color: theme.palette.grey[500],
  },
  accordion: {
    marginBottom: '16px',
    boxShadow: 'none',
    '&::before': { display: 'none' },
    border: '2px solid #F1F5FA',
    borderRadius: 3,
  },
  accordion_summary: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    borderRadius: 3,
  },
  filters_wrapper_header: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: '20px',
  },
  filters_title: {
    fontSize: { xs: '14px', sm: '14px', md: '18px', lg: '18px' },
    fontWeight: 500,
  },
  remove_filters_button: {
    width: { xs: '100px', sm: '100px', md: '120px', lg: '120px' },
    height: { xs: '28px', sm: '28px', md: '32px', lg: '32px' },
    borderRadius: '8px',
    fontSize: { xs: '12px', sm: '12px', md: '14px', lg: '14px' },
    fontWeight: 500,
    boxShadow: '0',
    backgroundColor: '#c20400',
    ':hover': { boxShadow: 'none' },
  },
  accordion_details: {
    padding: { xs: '14px', sm: '14px', md: '18px', lg: '18px' },
  },
  filter_inputs_container: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  filter_inputs_patch: {
    width: '100%',
    display: 'flex',
    flexDirection: { xs: 'column', sm: 'column', md: 'row', lg: 'row' },
    gap: '20px',
  },
  table_buttons_container: {
    position: 'relative',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  add_button: {
    fontSize: '14px',
    fontWeight: 600,
    borderWidth: '2px',
    borderRadius: '8px',
    width: '140px',
    height: '40px',
    color: theme.palette.common.black,
    backgroundColor: 'rgb(203, 203, 236)',
    boxShadow: 'none',
    ':hover': { boxShadow: 'none' },
  },
  refresh_button_container: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '40px',
    width: '40px',
    bgcolor: 'rgb(203, 203, 236)',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  refresh_button: { fontSize: 20, color: theme.palette.common.black },

  accounting_box: {
    position: 'relative',
    width: '100%',
    maxWidth: { xs: '100%', lg: '1100px', xl: '1140px' },
    margin: { xs: '10px 0', lg: '20px auto' },
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: { xs: '16px', lg: '16px' },
    justifyContent: 'center',
  },
  accounting_item_cell: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  item_box: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    justifyContent: 'center',
    minHeight: '140px',
    width: '100%',
    maxWidth: '320px',
    padding: '18px 20px 18px 28px',
    borderRadius: '16px',
    border: '1px solid rgba(203, 175, 113, 0.35)',
    background: 'linear-gradient(135deg, rgba(203, 175, 113, 0.18), rgba(255,255,255,0.98))',
    boxShadow: '0 15px 40px rgba(10, 16, 34, 0.04)',
    overflow: 'hidden',
    '&:before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background: 'radial-gradient(circle at top right, rgba(203,175,113,0.35), transparent 50%)',
      opacity: 0.9,
      pointerEvents: 'none',
    },
  },
  item_box_rial: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    justifyContent: 'center',
    minHeight: '140px',
    width: '100%',
    maxWidth: '320px',
    padding: '18px 20px 18px 28px',
    borderRadius: '16px',
    border: '1px solid rgba(113, 128, 203, 0.35)',
    background: 'linear-gradient(135deg, rgba(113, 128, 203, 0.18), rgba(255,255,255,0.98))',
    boxShadow: '0 15px 40px rgba(10, 16, 34, 0.04)',
    overflow: 'hidden',
    '&:before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background: 'radial-gradient(circle at top right, rgba(113, 128, 203,0.35), transparent 50%)',
      opacity: 0.9,
      pointerEvents: 'none',
    },
  },
  item_box_header: {
    position: 'relative',
    display: 'flex',
    gap: '10px',
    zIndex: 1,
  },
  item_box_indicator: {
    width: '12px',
    height: '12px',
    minWidth: '12px',
    maxHeight: '12px',
    borderRadius: '50%',
    backgroundColor: '#cbaf71',
    boxShadow: '0 0 10px rgba(203, 175, 113, 0.6)',
    marginTop: '4px',
  },
  item_box_indicator_rial: {
    width: '12px',
    height: '12px',
    minWidth: '12px',
    maxHeight: '12px',
    borderRadius: '50%',
    backgroundColor: 'rgb(135, 154, 238)',
    boxShadow: '0 0 10px rgba(126, 144, 227, 0.6)',
    marginTop: '4px',
  },
  item_title: {
    fontSize: { xs: '13px', sm: '13px', md: '14px', lg: '15px' },
    fontWeight: 600,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
    color: theme.palette.text.secondary,
    zIndex: 1,
  },
  item_value: {
    position: 'relative',
    fontSize: { xs: '18px', sm: '20px', md: '22px', lg: '24px' },
    fontWeight: 700,
    color: theme.palette.text.primary,
    zIndex: 1,
    textAlign: 'left',
    direction: 'ltr',
    unicodeBidi: 'isolate',
  },
};

export default SX;
